//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluetoothDMM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluetoothDMM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Software.
        /// </summary>
        public static string AboutSoftware {
            get {
                return ResourceManager.GetString("AboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MAC Adress as Sub Directory.
        /// </summary>
        public static string AddMacAdress {
            get {
                return ResourceManager.GetString("AddMacAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvencedSettings {
            get {
                return ResourceManager.GetString("AdvencedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        public static string AlwaysonTop {
            get {
                return ResourceManager.GetString("AlwaysonTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Analog Display on Startup.
        /// </summary>
        public static string AnalogDisplatONStart {
            get {
                return ResourceManager.GetString("AnalogDisplatONStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Display.
        /// </summary>
        public static string AnalogDisplay {
            get {
                return ResourceManager.GetString("AnalogDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Before Connect.
        /// </summary>
        public static string AskBeforeConnect {
            get {
                return ResourceManager.GetString("AskBeforeConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Connect Known Devices on Startup.
        /// </summary>
        public static string AutoConnectKnown {
            get {
                return ResourceManager.GetString("AutoConnectKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Range.
        /// </summary>
        public static string AutoRange {
            get {
                return ResourceManager.GetString("AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of your device is Available to connect..
        /// </summary>
        public static string AvailableString {
            get {
                return ResourceManager.GetString("AvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Device Name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data Chart on Startup.
        /// </summary>
        public static string ChartON {
            get {
                return ResourceManager.GetString("ChartON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chart.
        /// </summary>
        public static string ClearChart {
            get {
                return ResourceManager.GetString("ClearChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID :.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Device.
        /// </summary>
        public static string ConnectToDevice {
            get {
                return ResourceManager.GetString("ConnectToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set CSV to default for Export.
        /// </summary>
        public static string CSVFirst {
            get {
                return ResourceManager.GetString("CSVFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Chart.
        /// </summary>
        public static string DataChart {
            get {
                return ResourceManager.GetString("DataChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Devices.
        /// </summary>
        public static string DeviceManager {
            get {
                return ResourceManager.GetString("DeviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Picker.
        /// </summary>
        public static string DevicePicker {
            get {
                return ResourceManager.GetString("DevicePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Ask again. Connect Automaticly..
        /// </summary>
        public static string DontAsk {
            get {
                return ResourceManager.GetString("DontAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Connect.
        /// </summary>
        public static string DontConnect {
            get {
                return ResourceManager.GetString("DontConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MQTT Client.
        /// </summary>
        public static string EnableMQTT {
            get {
                return ResourceManager.GetString("EnableMQTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INRUSH.
        /// </summary>
        public static string InRush {
            get {
                return ResourceManager.GetString("InRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Available!.
        /// </summary>
        public static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Available Devices:.
        /// </summary>
        public static string ListAvailDevices {
            get {
                return ResourceManager.GetString("ListAvailDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Raw Data.
        /// </summary>
        public static string LogRaw {
            get {
                return ResourceManager.GetString("LogRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bluetooth Devices.
        /// </summary>
        public static string ManageDevices {
            get {
                return ResourceManager.GetString("ManageDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Known Devices.
        /// </summary>
        public static string ManageKnown {
            get {
                return ResourceManager.GetString("ManageKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Minimize to Tray.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Server Adress :.
        /// </summary>
        public static string MQTTAdress {
            get {
                return ResourceManager.GetString("MQTTAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Data Values Format.
        /// </summary>
        public static string MQTTDataFormat {
            get {
                return ResourceManager.GetString("MQTTDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Settings.
        /// </summary>
        public static string MQTTSettings {
            get {
                return ResourceManager.GetString("MQTTSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEEK.
        /// </summary>
        public static string Peek {
            get {
                return ResourceManager.GetString("Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reconnect after Disconnection.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Devices.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Device.
        /// </summary>
        public static string RemoveDevice {
            get {
                return ResourceManager.GetString("RemoveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset View.
        /// </summary>
        public static string ResetView {
            get {
                return ResourceManager.GetString("ResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Windows Startup.
        /// </summary>
        public static string RunStartup {
            get {
                return ResourceManager.GetString("RunStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Output:.
        /// </summary>
        public static string SampleOutput {
            get {
                return ResourceManager.GetString("SampleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Position and Size.
        /// </summary>
        public static string SavePosition {
            get {
                return ResourceManager.GetString("SavePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Bluetooth Devices....
        /// </summary>
        public static string SearchingDevices {
            get {
                return ResourceManager.GetString("SearchingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Settings.
        /// </summary>
        public static string StartupSettings {
            get {
                return ResourceManager.GetString("StartupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Topic :.
        /// </summary>
        public static string TargetTopic {
            get {
                return ResourceManager.GetString("TargetTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE RMS.
        /// </summary>
        public static string TrueRMS {
            get {
                return ResourceManager.GetString("TrueRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Login.
        /// </summary>
        public static string UseLogin {
            get {
                return ResourceManager.GetString("UseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version :.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Want to Connect?.
        /// </summary>
        public static string WantToConnect {
            get {
                return ResourceManager.GetString("WantToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom and Fit Data.
        /// </summary>
        public static string ZoomandFitData {
            get {
                return ResourceManager.GetString("ZoomandFitData", resourceCulture);
            }
        }
    }
}
